version: '3.6'
services:
  
  mongo:
    image: mongo
    networks:
      - backend
    container_name: insurance-quote
    ports:  
      - 27017:27017
    volumes:
      - $HOME/data/insurance-quote-data:/data/db
      - $HOME/data/insurance-quote-bkp:/data/bkp
    restart: always
  
  rabbitmq:
    image: rabbitmq:management
    networks:
      - backend
    container_name: insurance-queue
    ports:
      - 5672:5672  
      - 15672:15672
    restart: always  
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: insurance-search
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data1
    ports:
      - 9200:9200
    networks:
      - backend 
      
volumes:
  esdata1:
    driver: local       
    
networks:
  backend:
      