version: '3.6'
services:
  
  mongo:
    image: mongo
    networks:
      - backend
    container_name: insurance-quote
    ports:  
      - 27017:27017
    volumes:
      - $HOME/data/insurance-quote-data:/data/db
      - $HOME/data/insurance-quote-bkp:/data/bkp
    restart: always
  
  rabbitmq:
    image: rabbitmq:management
    networks:
      - backend
    container_name: insurance-queue
    ports:
      - 5672:5672  
      - 15672:15672
    restart: always  
    
networks:
  frontend:
  backend:
      